version: 2.1
orbs:
  node: circleci/node@6.1.0
jobs:
  lint-and-ts:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn typescript
workflows:
  build-and-test:
    jobs:
      - lint-and-ts
